export const fields = {
  type: {
    type: 'selectwithfeedback',
    renderAsTag: true,
    options: [
      { value: 'People', label: 'People', color: 'magenta' },
      { value: 'Company', label: 'Company', color: 'blue' },
    ],
    required: true,
    hasFeedback: true,
  },
  company: {
    type: 'search',
    label: 'company',
    entity: 'company',
    displayLabels: ['name'],
    searchFields: 'name',
    dataIndex: ['company', 'name'],
    disableForTable: true,
    feedback: 'Company',
  },
  people: {
    type: 'search',
    label: 'people',
    entity: 'people',
    displayLabels: ['firstname', 'lastname'],
    searchFields: 'firstname,lastname',
    dataIndex: ['people', 'firstname'],
    disableForTable: true,
    // feedback: 'People',
  },
  name: {
    type: 'string',
    disableForForm: true,
    dataIndex: ['admin', 'name'],
  },
  phone: {
    type: 'phone',
    disableForForm: true,
    displayLabels: ['phone'],
    dataIndex: ['people', 'phone'],
  },
  email: {
    type: 'email',
    required: true,
    displayLabels: ['email'],
    dataIndex: ['admin', 'email'],
  },
  password: {
    type: 'password',
    required: true,
    renderAsTag: true,
    disableForTable: true,
  },
  country: {
    type: 'string',
    // color: 'red',
    disableForForm: true,
    displayLabels: ['country'],
    dataIndex: ['people', 'country'],
  },

  role: {
    type: 'selectRoles',
    renderAsTag: true,
    required: true,
    hasRoles: true,
    disableForTable: true,
  },
  enabled: {
    type: 'boolean',
    renderAsTag: true,
    required: true,
    disableForTable: true,
  },
};
