const color = [
  { value: 'default', label: 'default' },
  { value: 'magenta', label: 'Magenta', color: 'magenta' },
  { value: 'red', label: 'Red', color: 'red' },
  { value: 'volcano', label: 'volcano', color: 'volcano' },
  { value: 'orange', label: 'Orange', color: 'orange' },
  { value: 'gold', label: 'Gold', color: 'gold' },
  { value: 'lime', label: 'Lime', color: 'lime' },
  { value: 'green', label: 'Green', color: 'green' },
  { value: 'cyan', label: 'Cyan', color: 'cyan' },
  { value: 'blue', label: 'Blue', color: 'blue' },
  { value: 'geekblue', label: 'Geekblue', color: 'geekblue' },
  { value: 'purple', label: 'Purple', color: 'purple' },
  { value: '#F2BED1', label: 'Pink', color: '#F2BED1' },
  { value: '#222', label: 'Black', color: '#222' },
  { value: '#999', label: 'Gray', color: '#999' },
  { value: '#31304D', label: 'Dark gray', color: '#31304D' },
  { value: '#C69774', label: 'Brown', color: '#C69774' },
  { value: '#FFC436', label: 'Yellow', color: '#FFC436' },
  { value: '#637E76', label: 'Dark green', color: '#637E76' },
  { value: '#29ADB2', label: 'Turquoise', color: '#29ADB2' },
  { value: '#FFAD84', label: 'Coral', color: '#FFAD84' },
  { value: '#B6BBC4', label: 'Silver', color: '#B6BBC4' },
  { value: '#392467', label: 'Violet', color: '#392467' },
  { value: '#A367B1', label: 'Berry', color: '#A367B1' },
  { value: '#88AB8E', label: 'Olive', color: '#88AB8E' },
  { value: '#0F2167', label: 'Navy', color: '#0F2167' },
  { value: '#4CB9E7', label: 'Aqua', color: '#4CB9E7' },
  { value: '#DED0B6', label: 'Beige', color: '#DED0B6' },
  { value: '#8A2BE2', label: 'Blue violet', color: '#8A2BE2' },
  { value: '#DEB887', label: 'Burlywood', color: '#DEB887' },
  { value: '#5F9EA0', label: 'Cadet blue', color: '#5F9EA0' },
  { value: '#D2691E', label: 'Chocolate', color: '#D2691E' },
  { value: '#DC143C', label: 'Crimson', color: '#DC143C' },
  { value: '#00008B', label: 'Dark blue', color: '#00008B' },
  { value: '#008B8B', label: 'Dark cyan', color: '#008B8B' },
  { value: '#B8860B', label: 'Dark goldenrod', color: '#B8860B' },
  { value: '#A9A9A9', label: 'Dark gray', color: '#A9A9A9' },
  { value: '#006400', label: 'Dark green', color: '#006400' },
  { value: '#BDB76B', label: 'dark khaki', color: '#BDB76B' },
  { value: '#8B008B', label: 'Dark magenta', color: '#8B008B' },
  { value: '#556B2F', label: 'Dark olive green', color: '#556B2F' },
  { value: '#FF8C00', label: 'Dark orange', color: '#FF8C00' },
  { value: '#9932CC', label: 'Dark orchid', color: '#9932CC' },
  { value: '#C70039', label: 'Dark red', color: '#C70039' },
  { value: '#E9967A', label: 'Dark salmon', color: '#E9967A' },
  { value: '#8FBC8F', label: 'dark sea green', color: '#8FBC8F' },
  { value: '#483D8B', label: 'Dark slate blue', color: '#483D8B' },
  { value: '#2F4F4F', label: 'Dark slate gray', color: '#2F4F4F' },
  { value: '#00CED1', label: 'Dark turquoise', color: '#00CED1' },
  { value: '#9400D3', label: 'Dark violet', color: '#9400D3' },
  { value: '#FF1493', label: 'Deep pink', color: '#FF1493' },
  { value: '#00BFFF', label: 'Deep sky blue', color: '#00BFFF' },
  { value: '#696969', label: 'Dim gray', color: '#696969' },
  { value: '#1E90FF', label: 'Dodger blue', color: '#1E90FF' },
];

export default color;
